### ISSUE TITLE
[崩溃] <标题内容> KTMPR_Alpha0.06f  打开背包用jei按u键查矿石的合成就会崩溃，重新打开存档物品贴图全部错误

### ISSUE THREAD

**Issue by 2237448629** [Kzeroko/Project-KTMPR-modpack#10]
## 基本信息收集
* 整合包版本：（整合包安装包和窗口标题都有写）

* 如何重现崩溃：（如果可以尽量详细说明）

### 上传你的崩溃报告
请在此粘贴你的崩溃错误报告-->
如果可以，请附带latest.log文件-->

### 如何获取错误报告？

<!---
【关于错误报告】
如果你不了解在哪里查看游戏的崩溃日志，你需要在以下文件夹内找到该文件
 "<整合包目录>/crash-reports/crash-<崩溃的具体时间>.txt"
请找到最后发生的错误报告上传，并确保其错误内容与本文有关联
如果你附带了latest.log文件，这将会提供很大帮助，你需要在以下文件夹内找到该文件
"<整合包目录>/logs/latest.log"

【请确保千万不要把错误报告的内容直接粘贴至本文！！！将文件拖动到本文对应位置即可】

**Comment by 2237448629** [comment]
[1.txt](https://github.com/Kzeroko/Project-KTMPR-modpack/files/9167626/1.txt)

Duplicate of #

**Comment by Kzeroko** [comment]
无法重现这个问题，不过下个版本会删除相关的模组，所以暂定为解决。
