### ISSUE TITLE
[崩溃] <未知原因崩溃>

### ISSUE THREAD

**Issue by NorthernLightt** [Kzeroko/Project-KTMPR-modpack#13]
## 基本信息收集
* 整合包版本：（整合包安装包和窗口标题都有写）

* 如何重现崩溃：（如果可以尽量详细说明）

-全屏游玩过程中无故崩溃
![捕获](https://user-images.githubusercontent.com/110146516/181421703-70cd0924-8c03-4dca-ac67-e04b6516623b.PNG)

-关闭全屏并取消自动分配后
![捕获](https://user-images.githubusercontent.com/110146516/181423331-5338c3af-febe-4510-83d0-9592b22613cb.PNG)

## 上传你的崩溃报告
请在此粘贴你的崩溃错误报告-->
-游戏没有退出到标题画面，而是直接崩溃，没有生成常规错误报告
[minecraft-exported-logs-2022-07-28T12-53-04.log](https://github.com/Kzeroko/Project-KTMPR-modpack/files/9205461/minecraft-exported-logs-2022-07-28T12-53-04.log)

如果可以，请附带latest.log文件-->
-文件30MB，超过25MB无法上传

#崩溃页面导出的额外文件 
[minecraft-exported-crash-info-2022-07-28T12-58-33.zip](https://github.com/Kzeroko/Project-KTMPR-modpack/files/9205478/minecraft-exported-crash-info-2022-07-28T12-58-33.zip)

### 如何获取错误报告？

<!---
【关于错误报告】
如果你不了解在哪里查看游戏的崩溃日志，你需要在以下文件夹内找到该文件
 "<整合包目录>/crash-reports/crash-<崩溃的具体时间>.txt"
请找到最后发生的错误报告上传，并确保其错误内容与本文有关联
如果你附带了latest.log文件，这将会提供很大帮助，你需要在以下文件夹内找到该文件
"<整合包目录>/logs/latest.log"

【请确保千万不要把错误报告的内容直接粘贴至本文！！！将文件拖动到本文对应位置即可】

**Comment by NorthernLightt** [comment]
如果可以的话，请告诉我如何在创造模式下解除系统限制，因为我想试一试特殊武器之类的，谢谢。

**Comment by Kzeroko** [comment]
显存爆了，电脑配置过低
