### ISSUE TITLE
[崩溃] <标题内容>

### ISSUE THREAD

**Issue by zate03** [Kzeroko/Project-KTMPR-modpack#15]
[minecraft-exported-crash-info-2022-08-01T12-40-38.zip](https://github.com/Kzeroko/Project-KTMPR-modpack/files/9230929/minecraft-exported-crash-info-2022-08-01T12-40-38.zip)

**Comment by Kzeroko** [comment]
请不要使用java17启动1.16.5的游戏，使用推荐的java1.8.301
