### ISSUE TITLE
[崩溃] <标题内容>

### ISSUE THREAD

**Issue by aimerdaisuke** [Kzeroko/Project-KTMPR-modpack#16]
## 基本信息收集
* 整合包版本：（1.16.5.Forge 36.2.35.OptiFine G8）

* 如何重现崩溃：（游戏可以加载到主界面 但是加载地图之后后过会就会无响应然后显示崩溃昨天还没有这种情况出现 ）

### 上传你的崩溃报告
请在此粘贴你的崩溃错误报告-->
[crash-2022-08-08_15.31.00-server.txt](https://github.com/Kzeroko/Project-KTMPR-modpack/files/9297961/crash-2022-08-08_15.31.00-server.txt)

如果可以，请附带latest.log文件-->
[latest.log](https://github.com/Kzeroko/Project-KTMPR-modpack/files/9297962/latest.log)

### 如何获取错误报告？

<!---
【关于错误报告】
如果你不了解在哪里查看游戏的崩溃日志，你需要在以下文件夹内找到该文件
 "<整合包目录>/crash-reports/crash-<崩溃的具体时间>.txt"
请找到最后发生的错误报告上传，并确保其错误内容与本文有关联
如果你附带了latest.log文件，这将会提供很大帮助，你需要在以下文件夹内找到该文件
"<整合包目录>/logs/latest.log"

【请确保千万不要把错误报告的内容直接粘贴至本文！！！将文件拖动到本文对应位置即可】

**Comment by Kzeroko** [comment]
是和 冰与火 龙寻路AI有关的崩溃，这个bug不是每个人都有，等作者修复吧
[https://github.com/Alex-the-666/Ice_and_Fire/issues/4606](url)
