### ISSUE TITLE
[崩溃] <标题内容>游戏安装失败 Caused By: 下载 Forge 36.2.35失败 Caused By: 安装 Mod 加载器（方式 A）失败 Caused By: 安装新 Forge 版本失败 Caused By: Forge 安装器出错，末行为 false    在 PCL.ModDownloadLib._Closure$__33-0._Lambda$__4(LoaderTask`2 Task)    在 PCL.ModLoader.LoaderTask`2._Closure$__12-0._Lambda$__0()    在 PCL.ModDownloadLib.ForgeInjector(String Target, LoaderTask`2 Task, String McFolder)    在 PCL.ModDownloadLib._Closure$__33-0._Lambda$__4(LoaderTask`2 Task)

### ISSUE THREAD

**Issue by RATIONAL-FISH** [Kzeroko/Project-KTMPR-modpack#17]
## 基本信息收集
* 整合包版本：（整合包安装包和窗口标题都有写）

* 如何重现崩溃：（如果可以尽量详细说明）

### 上传你的崩溃报告
请在此粘贴你的崩溃错误报告-->
如果可以，请附带latest.log文件-->

### 如何获取错误报告？

<!---
【关于错误报告】
如果你不了解在哪里查看游戏的崩溃日志，你需要在以下文件夹内找到该文件
 "<整合包目录>/crash-reports/crash-<崩溃的具体时间>.txt"
请找到最后发生的错误报告上传，并确保其错误内容与本文有关联
如果你附带了latest.log文件，这将会提供很大帮助，你需要在以下文件夹内找到该文件
"<整合包目录>/logs/latest.log"

【请确保千万不要把错误报告的内容直接粘贴至本文！！！将文件拖动到本文对应位置即可】

**Comment by Kzeroko** [comment]
请更换 启动器/下载源，或是多尝试几次来解决这个问题
