### ISSUE TITLE
[崩溃] JVM加载类失败

### ISSUE THREAD

**Issue by 2Jian** [Kzeroko/Project-KTMPR-modpack#5]
## 基本信息收集
* 整合包版本：（整合包安装包和窗口标题都有写）
KTMPR_Alpha0.04
* 如何重现崩溃：（如果可以尽量详细说明）
正常启动就会报错，我的.minecraft文件是从另一个1.12.2的整合包里复制过来的，启动器用的是PCL2.2.11，forge是在官网下的36.2.34版本，另加了一个OptiFine。
![image](https://user-images.githubusercontent.com/105573744/168455271-89ec5bbc-50cc-4425-bda5-2c143cfd9149.png)

### 上传你的崩溃报告
请在此粘贴你的崩溃错误报告-->
[crash-2022-05-15_10.22.46-fml.txt](https://github.com/Kzeroko/Project-KTMPR-modpack/files/8694221/crash-2022-05-15_10.22.46-fml.txt)

如果可以，请附带latest.log文件-->
[latest.log](https://github.com/Kzeroko/Project-KTMPR-modpack/files/8694222/latest.log)

### 如何获取错误报告？

<!---
【关于错误报告】
如果你不了解在哪里查看游戏的崩溃日志，你需要在以下文件夹内找到该文件
 "<整合包目录>/crash-reports/crash-<崩溃的具体时间>.txt"
请找到最后发生的错误报告上传，并确保其错误内容与本文有关联
如果你附带了latest.log文件，这将会提供很大帮助，你需要在以下文件夹内找到该文件
"<整合包目录>/logs/latest.log"

【请确保千万不要把错误报告的内容直接粘贴至本文！！！将文件拖动到本文对应位置即可】

**Comment by Kzeroko** [comment]
这个整合包暂时只支持使用**Java8_u301**版本启动，如果你在我的官方群聊678068648，群文件的新包文件夹有提供该版本的下载。
记得进入游戏前在设置中修改当前整合包的启动Java版本。
如果还有问题欢迎在此issue中回复

**Comment by Kzeroko** [comment]
请尝试通过导入的方式重新安装整合包，具体步骤如下：
1. 下载群内的整合包压缩文件
2. 将压缩文件原封不动拖到启动器窗口界面，这边推荐hmcl启动器
    （Pcl也可以通过导入整合包的方式安装） 
3. 按照启动器给出的步骤安装，记得重新设置启动的java版本

如果还出现该问题，欢迎继续在此issue中回复

**Comment by 2Jian** [comment]
![image](https://user-images.githubusercontent.com/105573744/168602114-43bfdf14-24b5-4eb1-9b23-a2d0716f3294.png)
![image](https://user-images.githubusercontent.com/105573744/168604131-c7836267-b4a2-42fc-b0c5-ce2f80e28cc9.png)
[PCL错误报告.txt](https://github.com/Kzeroko/Project-KTMPR-modpack/files/8700442/PCL.txt)
又是我，我把压缩文件拖入启动器后，可以正常下载，每次都是到安装forge的时候，他会报如图错误，所以之前我才会想着自己在官网下forge。请问这是不是我的电脑的问题，希望您看看能否给我提供解决方案。您没时间的话就不用了，我自己也在尝试解决。 @Kzeroko

**Comment by Kzeroko** [comment]
> 

看到了，你有否尝试过更换下载源呢

如果实在不行可以通过更换启动器来解决，这种事情在玩家群体经常发生，尝试上述的方法基本都能解决

如果还有问题欢迎回复

**Comment by Kzeroko** [comment]
由于未回复，将关闭该issue
