### ISSUE TITLE
[崩溃] <标题内容>打开菜单时的崩溃

### ISSUE THREAD

**Issue by Polyethylenekjc** [Kzeroko/Project-KTMPR-modpack#8]
## 基本信息收集
* 整合包版本：（整合包安装包和窗口标题都有写）
Alpha V0.06f
* 如何重现崩溃：（如果可以尽量详细说明）
新建世界后进入游戏，在刀剑菜单中选择进入菜单后崩溃。

### 上传你的崩溃报告
请在此粘贴你的崩溃错误报告-->
[crash-2022-06-04_13.29.24-client.txt](https://github.com/Kzeroko/Project-KTMPR-modpack/files/8837083/crash-2022-06-04_13.29.24-client.txt)
如果可以，请附带latest.log文件-->

日志文件过大分成了两份
[part2.log](https://github.com/Kzeroko/Project-KTMPR-modpack/files/8837109/part2.log)
[part1.log](https://github.com/Kzeroko/Project-KTMPR-modpack/files/8837108/part1.log)

### 如何获取错误报告？

<!---
【关于错误报告】
如果你不了解在哪里查看游戏的崩溃日志，你需要在以下文件夹内找到该文件
 "<整合包目录>/crash-reports/crash-<崩溃的具体时间>.txt"
请找到最后发生的错误报告上传，并确保其错误内容与本文有关联
如果你附带了latest.log文件，这将会提供很大帮助，你需要在以下文件夹内找到该文件
"<整合包目录>/logs/latest.log"

【请确保千万不要把错误报告的内容直接粘贴至本文！！！将文件拖动到本文对应位置即可】

**Comment by Polyethylenekjc** [comment]
![image](https://user-images.githubusercontent.com/77469379/171986610-fa60bd3e-00bc-42ba-91ec-bf027d87a95a.png)
崩溃触发的具体位置

**Comment by Kzeroko** [comment]
无法重现该bug，SAOui模组当前还处于beta阶段，兼容性较差且问题较多。
如果出现类似问题，推荐重启游戏。
后续如果受不了各种bug不希望继续使用SAOui，我会单独出一个非UI的版本提供下载。

将关闭当前issue，如果出现新的bug欢迎汇报~
