### ISSUE TITLE
[崩溃] <标题内容>

### ISSUE THREAD

**Issue by MLYCXL** [Kzeroko/Project-KTMPR-modpack#9]
[latest.log](https://github.com/Kzeroko/Project-KTMPR-modpack/files/9121624/latest.log)

**Comment by Kzeroko** [comment]
有没有尝试过更换启动器启动游戏？

这份log文件提供的信息不是很足，如果可以的话能否提供导出的启动器日志。

**Comment by Kzeroko** [comment]
由于未回复，将关闭该issue
